### ISSUE TITLE
EssentialCraft and ExtraBiomes conflict

### ISSUE THREAD

**Issue by 1skandar** [Modbder/EssentialCraft3#27]
Unfortunately, I have no hard evidence because nothing is going to the logs but something has gone very wrong.

With both EssentialCraft and ExtraBiomes together villages almost do not spawn. You will get maybe 1 village in several thousand blocks and that village is ALWAYS just 2 structures. You also get massive, massive chunk ticking lag.

I'm not sure what is going on and I wish I could offer more hard evidence here, but something is decidedly screwy.

**Comment by Modbder** [comment]
Can you use OPIS to check what is causing chunk tick lag? This part of your problem is the only one that can be caused by EC3, since EC3 is a pretty performance-heavy mod, and there might be an error in the code somewhere that causes lag. Since I haven't experienced it - I need some data to work with. Warmroast will also work just fine.

EC3 does not modify villages in any way - I add absolutely no generation there, I track 0 generation events related to them, I don't even add new villagers - so I do not think that that problem is caused by EC3 in any way.

**Comment by Modbder** [comment]
Anyone here? Is the problem gone?

**Comment by 1skandar** [comment]
Unfortunately I've been unable to confirm or deny if a problem exists. Proving a negative is nearly impossible. Village generation appears to be impacted, but I haven't been able to nail that down exactly. It appears that villages are smaller and much further apart, but that might be just subjective which makes nailing a cause frustratingly difficult.

**Comment by 1skandar** [comment]
At this point I'll consider this closed. I'm still not sure something is up, but the evidence is so damn contradictory at this point I'm not sure anymore. Things are working ok at this point.

**Comment by Modbder** [comment]
If you find any evidence or at least a way to replicate the problem - feel free to open this issue.

**Comment by 1skandar** [comment]
Yeah. It is, at least, functional and I am sick and tired of creating new test worlds and not getting clear evidence one way or another...or worse conflicting evidence. 

If I can nail anything down I'll be back, but at this point I doubt it.
